### ISSUE TITLE
move to JuliaDiff?

### ISSUE THREAD

**Issue by mlubin** [JuliaDiff/TaylorSeries.jl#1]
It hasn't been formally announced, but we are building up an organization for differentiation tools called JuliaDiff: http://www.juliadiff.org/. This package seems like a good fit, so let me know if you're interested in moving it into the organization.

**Comment by lbenet** [comment]
@mlubin Sorry for the long long silence...

Few days ago I pushed into master a better version of `TaylorSeries.jl`, including docs, which you can find at http://lbenet.github.io/TaylorSeries.jl. There are still some things that will be improved, but we are slowly converging.

If you have some time, could you take a look and suggest improvements?

**Comment by mlubin** [comment]
This all looks good to me, definitely suitable to move over to JuliaDiff if you'd like.

**Comment by lbenet** [comment]
Sure!

**Comment by mlubin** [comment]
Done, you have permission to transfer ownership of the repo.

**Comment by lbenet** [comment]
So, shall I add it as a new repo?

**Comment by mlubin** [comment]
Go to settings -> options -> danger zone -> transfer ownership on this repo

**Comment by lbenet** [comment]
Sorry for my github lack of knowledge... The new repo owner, is it JuliaDiff?

**Comment by mlubin** [comment]
Yep, that should be it

**Comment by lbenet** [comment]
I think it's done

**Comment by lbenet** [comment]
Do you know if David Sanders will still be collaborator of this project? I still need to read more help pages...

cc @dpsanders

**Comment by mlubin** [comment]
Hmm, not quite. When it's done, the URLs will be redirected to JuliaDiff/TaylorSeries.jl instead of lbenet/TaylorSeries.jl.

You'll have permission to add collaborators to the project.

**Comment by lbenet** [comment]
Ok, so I will add him when the time comes. All this has been a collaborative work.

I guess i can close this...

**Comment by mlubin** [comment]
The repo hasn't been transferred yet

**Comment by lbenet** [comment]
Then, I may have done something wrong. The only two questions I needed to answer is the repo name (TaylorSeries.jl) and the new owner (JuliaDiff). Is this correct, or the repo name is TaylorSeries.jl.git ?

**Comment by mlubin** [comment]
The repo name is TaylorSeries.jl. Are there any error messages?

**Comment by lbenet** [comment]
No.

**Comment by lbenet** [comment]
Transfer just completed. I'm closing this.

**Comment by mlubin** [comment]
Great!

**Comment by lbenet** [comment]
@mlubin Do you know if I need to update the link in the badge of coveralls? Now it is still pointing out to the old github repo...

**Comment by mlubin** [comment]
Yes, I think coveralls doesn't transfer very smoothly. You may need to re-enable it for the new repo and update the badge link.
