### ISSUE TITLE
Use attobot

### ISSUE THREAD

**Issue by lbenet** [JuliaDiff/TaylorSeries.jl#108]
Hi @mlubin @jrevels,
I tried to use [Attobot](https://github.com/attobot/attobot) to tag the next version of TaylorSeries, but it seems I do not have the privileges to do so. When I try to configure it I get the "404 Page not found". Can you help me on that?

**Comment by mlubin** [comment]
I've just enabled attobot for this repo

**Comment by lbenet** [comment]
Thanks a lot!

**Comment by lbenet** [comment]
Closing, since I just submitted the new tag. Thanks!
