### ISSUE TITLE
Integration of Taylor series with several variables

### ISSUE THREAD

**Issue by dpsanders** [JuliaDiff/TaylorSeries.jl#130]
There doesn't seem to be "partial integration" of a Taylor series with respect to a single variable.

For example, if we have

```
f(a, t) = a + a*t
```

we should be able to integrate with respect to `t` in the interval `[0, τ]`

**Comment by lbenet** [comment]
You are definitely right; there is no method to integrate `TaylorN` series. At some point I was thinking about this, but was somehow distracted. I you have some time, please go ahead!

**Comment by lbenet** [comment]
Solved by #136; closing.
