### ISSUE TITLE
Taylor series around a non-zero point

### ISSUE THREAD

**Issue by dpsanders** [JuliaDiff/TaylorSeries.jl#138]
It is not clear to me how to represent a Taylor series around a non-zero point $t_0$, e.g.

$$a_0 + a_1 (t-t_0) + a_2 (t-t0)^2 + ...$$

**Comment by lbenet** [comment]
(Related to #114)

The usual way of writing this is ( I will use `x` and `x0`  as the independent variable and point of expansion, to avoid confusions) is

$$ f(x) = f_0 + f_1 (x-x0) + f_2 (x-x0)^2 + ... $$

which is precisely what you wrote. Here, the Taylor coefficients $ f_r $ are related to the r-th derivative of f at x0 and some factorial coefficients in the usual way. The important point here is that, a priori, $ x-x0 $ must be small enough to have convergence. 

In `TaylorSeries`, we essentially do the change t --> x - x0, so the expansion is written as

$$ f( x0+t ) = f_0 + f_1 t + f_2 t^2 + ... $$

We abuse of notation and f(x0+t) --> f(t), keeping in mind that we are expanding around `x0`. The point to keep in mind is that we need `t` to be small so the Taylor series converges. 

As an example, I will expand `sin` around `pi` and compare it with the expansion around `0`; the first is the negative of the second one.

```julia
julia> using TaylorSeries

julia> f(x) = sin(x)
f (generic function with 1 method)

julia> x0 = pi;

julia> t = Taylor1(10)  # independent variable; small excess with respect to x0
 1.0 t + 𝒪(t¹¹)

julia> f(x0+t)  # shift described above
 1.2246467991473532e-16 - 1.0 t - 6.123233995736766e-17 t² + 0.16666666666666666 t³ + 5.102694996447305e-18 t⁴ - 0.008333333333333333 t⁵ - 1.7008983321491017e-19 t⁶ + 0.0001984126984126984 t⁷ + 3.0373184502662533e-21 t⁸ - 2.7557319223985893e-6 t⁹ - 3.374798278073615e-23 t¹⁰ + 𝒪(t¹¹)

julia> f(x0+t)
 1.2246467991473532e-16 - 1.0 t - 6.123233995736766e-17 t² + 0.16666666666666666 t³ + 5.102694996447305e-18 t⁴ - 0.008333333333333333 t⁵ - 1.7008983321491017e-19 t⁶ + 0.0001984126984126984 t⁷ + 3.0373184502662533e-21 t⁸ - 2.7557319223985893e-6 t⁹ - 3.374798278073615e-23 t¹⁰ + 𝒪(t¹¹)

julia> f(x0+t) + sin(t)  # f(x0+t) = sin(pi+t) = -sin(t) 
 1.2246467991473532e-16 - 6.123233995736766e-17 t² + 5.102694996447305e-18 t⁴ - 1.7008983321491017e-19 t⁶ + 3.0373184502662533e-21 t⁸ - 3.374798278073615e-23 t¹⁰ + 𝒪(t¹¹)
```

If you evaluate the expansion for *small* t (say h), then you get the approximation for f(x0+h).

Let me know if this clarifies your question.

**Comment by dpsanders** [comment]
OK, I think I see what the problem is: I want the `Taylor1` object to contain the information about `x0`, so that evaluating it does effectively `f(x0 + t)`. 

Is there any reason why it wouldn't be a good idea to do this?

**Comment by dpsanders** [comment]
Or maybe I'm just confused...

**Comment by Wikunia** [comment]
I might got the point of @dpsanders Correct me if I'm wrong.
Let's assume we have

```
x = Taylor1(1) # very simple order
f(x) = sin(x)
# around point 0.1
a = f(x+0.1)
p = 0.1
@assert a(p-0.1) == sin(0.1)
```

**Comment by lbenet** [comment]
Thanks for your example! I hope the following contributes to clarify things.

The goal in your example is to evaluate `sin(0.5)` using the *order-1 Taylor expansion* of `sin` around 0.1, which corresponds to `a`. Then, you correctly evaluate `a(0.4)`. So far so good. Yet, what surprises you from `a(0.4)` is that `sin(0.5)` differs considerably from `a(0.4)` to be a good approximation.

The reason for the problem is that the order 1 Taylor expansion is *too short* to be able to provide a better result than the one you got. (Better it would have been to begin at 0.4.) If I repeat your example but using a 16th-order Taylor expansion, still around 0.1, I get the following:
```julia
julia> x = Taylor1(16)
 1.0 t + 𝒪(t¹⁷)

julia> a = f(x+0.1); 

julia> a(0.4)
0.47942553860420306

julia> sin(0.5)
0.479425538604203

julia> (a(0.4)-sin(0.5)) / eps( sin(0.5) )  # error in local machine epsilon units
1.0
```

There is indeed a small difference, but it is 1 local machine epsilon (around `sin(0.5)` away from the result, which is quite ok!

**Comment by lbenet** [comment]
@Wikunia Let me know if this clarifies better the issue...

**Comment by Wikunia** [comment]
Yes. I used order 1 to make it as simple as possible ;)

**Comment by lbenet** [comment]
Too simple, perhaps :-)
