### ISSUE TITLE
Partial `evaluate`ion

### ISSUE THREAD

**Issue by dpsanders** [JuliaDiff/TaylorSeries.jl#151]
Suppose I have a Taylor series `s` in 3 variables `x, y, z`.
I need to be able to evaluate `s` for some numerical value of `x`, and obtain as response a TaylorSeries in the two variables `y and z`. 

(It can still be a 3-variable series; it just won't have any monomials including any power of `x`.)

**Comment by dpsanders** [comment]
Example: `s = x^2 + x*y + y*z`.
Evaluation at `x=1` gives `1 + y + y*z`.

**Comment by dpsanders** [comment]
Presumably something like this is already present in TaylorIntegration.jl?

**Comment by dpsanders** [comment]
Neat, thanks! Yes, that would be nice.

**Comment by dpsanders** [comment]
Maybe `evaluate(s, :x=>1)`

and `p(:x=>1, :y=>2)` for a Taylor series `p`.

**Comment by lbenet** [comment]
#155 already allows to do things like `evaluate(p, :x, 1)`, which is equivalent to `p(:x, 1)`.

I'll see if I can make it work with the `Pair` as you propose.

**Comment by dpsanders** [comment]
Seems to be enough to do
```
evaluate(p, x::Pair) = evaluate(p, first(x), last(x))
```
or `evaluate(p, x[1], x[2])`

**Comment by lbenet** [comment]
I was almost there...
