### ISSUE TITLE
Functional API for Taylor getfield

### ISSUE THREAD

**Issue by jessebett** [JuliaDiff/TaylorSeries.jl#208]
At the moment the API to access coefficients and order of a `Taylor1` is though `getfield(t::Taylor1,:coeffs)` or `t.coeffs`. Same with order.

Can the API also have functions for these `coeffs(t)` and `order(t)` in the case of `Taylor1`. 

At the moment I'm working with arrays with type `Array{Taylor1{Float64},1}` and it is very frustrating to work with these. e.g. something as simple as getting the constant term is awful:
```
# broadcast getfield requires using full notation, not the convenient `t.coeffs`
# this returns an array of arrays where each element is the array of coefficients
getfield.(t,:coeffs) 

# since this is an array of arrays, getindex needs to be broadcasted as well
getindex.(getfield.(t,:coeffs),1) # first coeffs
```

Okay, admittedly just now writing up this issue I remembered that `getindex` is defined on `Taylor1` to return the coefficient (base 0, which got me before!) so the above simplifies to `getindex.(t,0)` which isn't so bad for `coeffs` but `order` is still ugly. `coeffs.(t,0)` would be much nicer.

Further, at the moment Zygote custom adjoints for `getfield` on different types isn't the nicest. I don't know if Mike has improved that situation much recently. But it will probably always be easier to write custom adjoints on functions. Having `TaylorSeries.coeffs` and `TaylorSeries.order` unexported but used internally might make plugging into AD also easier, as well as massively clean up working with arrays of Taylors.

**Comment by lbenet** [comment]
Let me first understand your suggestion: you would like some way of getting the `coeff` and `order` parts of a `Taylor1` polynomial through a function. Is that correct? 

We already have the function `get_order(t)`, which returns `t.order`, which may interest you. 

As you point out, `getindex` was extended, and we have `getcoeffs(t, n)` which returns `t[n]`, so the order n coefficient of the polynomial. It is easy to extend `getcoeff(t)` (or rather `getcoeffs(t)`) which would return the whole vector of coefficients.

**Comment by lbenet** [comment]
Did using `getcoeff` and `get_order` help you solve your problem?

**Comment by jessebett** [comment]
Ah! I missed these in the API documentation because I was searching quickly for `coeffs` not `coeff`. This solves my problem. Thanks @lbenet!

**Comment by lbenet** [comment]
You are welcome!
