### ISSUE TITLE
Custom printing for Taylor1

### ISSUE THREAD

**Issue by MasonProtter** [JuliaDiff/TaylorSeries.jl#211]
Currently, with `TaylorN` you can choose to use whatever string you want for the power series variable printing, however it seems that `Taylor1`s are stuck with the letter `t` for their printing. It'd be nice if this was customizable.

**Comment by lbenet** [comment]
You are absolutely right! I have encountered that problem myself. If you have some time, please go ahead and submit a PR.

**Comment by lbenet** [comment]
Sorry for the long delay to address this; this is finally implemented in #219

**Comment by lbenet** [comment]
@dpsanders Do you agree to go ahead and merge this?

**Comment by lbenet** [comment]
Ups... the last message should have gone to #229 ...
