### ISSUE TITLE
Install Registrator and TagBot

### ISSUE THREAD

**Issue by lbenet** [JuliaDiff/TaylorSeries.jl#212]
Hi @mlubin Can you install [Registrator](https://github.com/JuliaRegistries/Registrator.jl) and [TagBot](https://github.com/JuliaRegistries/TagBot) for `TaylorSeries.jl`? I don't have permissions to do that. Thanks in advance!

**Comment by mlubin** [comment]
It's already enabled on JuliaDiff :)

**Comment by lbenet** [comment]
I didn't know! Thanks a lot anyway!
