### ISSUE TITLE
Tag v0.10.0

### ISSUE THREAD

**Issue by lbenet** [JuliaDiff/TaylorSeries.jl#217]

**Comment by lbenet** [comment]
@JuliaRegistrator register

**Comment by dpsanders** [comment]
I believe that this is no longer the correct procedure. Now you need to use Registrator and tagbot I believe? And put the new version number in Project.toml

**Comment by dpsanders** [comment]
Ah, exactly ;)

**Comment by lbenet** [comment]
Sorry if I am too fast on this. We need a chain of new releases to allow certain developments within JuliaReach (e.g., https://github.com/JuliaReach/LazySets.jl/pull/1408)

**Comment by lbenet** [comment]
I guess we will need to be a bit patient to see if [TagBot](https://github.com/JuliaRegistries/TagBot) does its job, or if we need to do it manually.

**Comment by lbenet** [comment]
It just worked! Closing!
