### ISSUE TITLE
Displayed equations in the docs are not displayed properly

### ISSUE THREAD

**Issue by lbenet** [JuliaDiff/TaylorSeries.jl#237]
See for example the current (v0.10.2) Background [page](https://www.juliadiff.org/TaylorSeries.jl/v0.10.2/background/). 

I guess this is related to the fact that HTML output renders equations with KaTeX as default.

EDIT: Explicited the current version of the package.

**Comment by dpsanders** [comment]
It still seems to be happening. Maybe the web page hasn't been updated yet? Thanks for addressing this!

**Comment by lbenet** [comment]
I just noticed it today; at least for the dev version it is fixed.
