### ISSUE TITLE
Math is not rendered in the document

### ISSUE THREAD

**Issue by newptcai** [JuliaDiff/TaylorSeries.jl#239]
This is what I see at http://www.juliadiff.org/TaylorSeries.jl/stable/examples/

```
\[\begin{eqnarray} (a_1+a_2+a_3+a_4)\cdot(b_1+b_2+b_3+b_4) & = & (a_1 b_1 - a_2 b_2 - a_3 b_3 -a_4 b_4)^2 + \qquad \nonumber \\ \label{eq:Euler} & & (a_1 b_2 - a_2 b_1 - a_3 b_4 -a_4 b_3)^2 + \\ & & (a_1 b_3 - a_2 b_4 - a_3 b_1 -a_4 b_2)^2 + \nonumber \\ & & (a_1 b_4 - a_2 b_3 - a_3 b_2 -a_4 b_1)^2, \nonumber \end{eqnarray}\]
```

**Comment by lbenet** [comment]
Thanks for reporting. This is similar to #237 and was solved by #238. For the time being (until a new version is tagged), I suggest to use the "dev" version of the documentation: https://www.juliadiff.org/TaylorSeries.jl/dev/

**Comment by dpsanders** [comment]
Can we tag a new patch version?

**Comment by lbenet** [comment]
I guess so; I didn't think it was worth to tag a new version which only changed something in the docs... I'll do it right away.

**Comment by lbenet** [comment]
Version 0.10.3 is tagged; you should be able to use the stable version of the documentation. Closing

**Comment by lbenet** [comment]
Reopening, because it is not yet there...

**Comment by dpsanders** [comment]
Tagging is easy and cheap so the recommendation now is that any change should be a new patch tag.

**Comment by lbenet** [comment]
I just checked it again, and it seems it does work! So, closing again.
