### ISSUE TITLE
Broken tests in Julia 1.6.0-beta1

### ISSUE THREAD

**Issue by lbenet** [JuliaDiff/TaylorSeries.jl#259]
Julia 1.6.0-beta1 has been released, so I've checked if tests were passing; there is one tests that doesn't, which [also happens in nightly](https://github.com/JuliaDiff/TaylorSeries.jl/pull/247/checks?check_run_id=1664984076#step:6:43)
```julia
Tests for Taylor1 expansions: Test Failed at /Users/benet/.julia/dev/TaylorSeries/test/onevariable.jl:398
  Expression: evaluate(v, complex(0.0, 0.2)) == [complex(0.0, sinh(0.2)), complex(cos(0.2), sin(-0.2))]
  Evaluated: ComplexF64[0.0 + 0.20133600254109402im, 0.9800665778412416 - 0.19866933079506122im] == ComplexF64[0.0 + 0.201336002541094im, 0.9800665778412416 - 0.19866933079506122im]
...
```
It seems to be a round-off issue.

**Comment by dpsanders** [comment]
I believe the implementation of `exp` has changed. Maybe report this as a JuliaLang issue? But it may just be rounding in the other direction.

**Comment by dpsanders** [comment]
On the plus side, the new version of exp is supposed to be 3 times faster.

**Comment by lbenet** [comment]
It only occurs for `Complex`es, so I guess it is the Horner implementation, which is special.

**Comment by lbenet** [comment]
Reported in https://github.com/JuliaLang/julia/issues/39230

**Comment by oscardssmith** [comment]
In addition to a new version of `exp` there is also a new version of `sinh` and `cosh`. All of these are faster and more accurate, but they do produce different outputs some of the time.
