### ISSUE TITLE
More clear documentation for basic users

### ISSUE THREAD

**Issue by KronosTheLate** [JuliaDiff/TaylorSeries.jl#276]
As a less competent user, both in terms of programming and math, I found the documentation pretty confusing and unhelpful. The first time the function I was looking for (`taylor_expand()`) was mentioned, was in the _end_  of the  "User guide/One independent variable" section. I feel like a basic example could be given much earlier.

Then there is the other way of doing things, where one defines a variable and uses that to compute taylor polynomials. This way of thinking and doing things only became clear to me in @dpsanders 's reply in [this discourse thread](https://discourse.julialang.org/t/find-taylor-series-of-a-function/51847/7), and not by the technically heavy documentation. For what it is worth, it seems like whoever created that discourse-post would agree with me that basic examples of how to expand e.g. `exp(x)` are not readily available in the current docs. A simple example like that given in the discourse discussion would be extremely appreciated at an early point.

The conclusion is that I found the documentation very techincal and heavy on math (like proving some identity I have never seen as the first example), and I would like to help remedy the situation. So I would like to write a section along the lines of "Just give me a Taylor series", with some basic usage examples. The problem is that I really do not see how such a section would fit in right now, other than perhaps shoehorned in before "One independent variable". I might give that a go, but the optimal solution would clearly be a more comprehensive rewrite, with basic examples baked into it.

**Comment by lbenet** [comment]
Thanks for open this issue and for proposing having a "Just give me a Taylor series" section in the documentation. I agree with you that the documentation needs to be improved, but I haven't found the time to do it. So your help is truly welcome and appreciated.

**Comment by KronosTheLate** [comment]
Good to hear! I am drawing great value for using all these amazing packages, so it truly is my pleasure to give somehing back.

I have added [this PR](https://github.com/JuliaDiff/TaylorSeries.jl/pull/277), which adds more or less what I was missing. I actually think that if these examples are added, the problem would almost be fixed by a reference to it. Something like `If you just want to compute a simple taylor-series, see the first examples under the section "Examples"` early in the `User guide`.

**Comment by lbenet** [comment]
Closed by #277
