### ISSUE TITLE
Matrix element type for `A*A'`

### ISSUE THREAD

**Issue by patkwee** [JuliaDiff/TaylorSeries.jl#303]
I run into the following issue, when calculating `A*A'` for a matrix `A` with element type of `TaylorN`. The resulting matrix has elements of type `Any`. I would have expected to get elements of type `TaylorN` back, or is this the wanted/expected behavior?

```julia
(ts) pkg> st
      Status `....ts\Project.toml`
  [6aa5eb33] TaylorSeries v0.12.1

julia> using TaylorSeries

julia> x, y = set_variables("x y", order=2);

julia> A = [1.0 + x 0.1; 0.1 1.0 + y]
2×2 Matrix{TaylorN{Float64}}:
  1.0 + 1.0 x + 𝒪(‖x‖³)            0.1 + 𝒪(‖x‖¹)
          0.1 + 𝒪(‖x‖¹)    1.0 + 1.0 y + 𝒪(‖x‖³)

julia> A'
2×2 adjoint(::Matrix{TaylorN{Float64}}) with eltype TaylorN:
  1.0 + 1.0 x + 𝒪(‖x‖³)            0.1 + 𝒪(‖x‖¹)
          0.1 + 𝒪(‖x‖¹)    1.0 + 1.0 y + 𝒪(‖x‖³)

julia> A*A'
2×2 Matrix{Any}:
  1.01 + 2.0 x + 1.0 x² + 𝒪(‖x‖³)      0.2 + 0.1 x + 0.1 y + 𝒪(‖x‖³)
    0.2 + 0.1 x + 0.1 y + 𝒪(‖x‖³)    1.01 + 2.0 y + 1.0 y² + 𝒪(‖x‖³)

julia> versioninfo()
Julia Version 1.7.2
Commit bf53498635 (2022-02-06 15:21 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-12.0.1 (ORCJIT, skylake)
Environment:
  JULIA_EDITOR = code
  JULIA_NUM_THREADS = 4
```

**Comment by lbenet** [comment]
Thanks for reporting. 

I can indeed reproduce the situation in both, Julia v1.7.3 and v1.8.0. Yet, I don't think the problem lies in `TaylorSeries.jl`, since `A * A'` uses a method from `LinearAlgebra.jl`. Using Julia v1.7.3 I get
```julia
julia> @which A * A'
*(A::AbstractMatrix, B::AbstractMatrix) in LinearAlgebra at /usr/local/julia/julia-1.7.3/share/julia/stdlib/v1.7/LinearAlgebra/src/matmul.jl:151
```
while in Julia 1.8.0 the method used corresponds to `/usr/local/julia/julia-1.8.0/share/julia/stdlib/v1.8/LinearAlgebra/src/matmul.jl:139`.

cc @dkarrasch

**Comment by dkarrasch** [comment]
Has it ever been different? I can reproduce even on v1.6. The reason is that the eltype of `A'` is `TaylorN`, not `TaylorN{Float64}`. I think I have a fix.
