### ISSUE TITLE
Taylor1 with empty vector

### ISSUE THREAD

**Issue by qwertyjl** [JuliaDiff/TaylorSeries.jl#305]
In my opinion this should give a readable error
```julia
a = Float64[]
# code
# code
t = Taylor1(a) # Error BoundsError: attempt to access 0-element Vector{Float64} at index [1]
```

**Comment by lbenet** [comment]
Thanks for reporting the lack of a readable error. 

The error is thrown somewhere in the printing process of `t`. With this I want to communicate two things: First, `t = Taylor1(a);` throws no error. Second, the error corresponds to the error you get for `a[1]`.
