### ISSUE TITLE
Implementation for log1p?

### ISSUE THREAD

**Issue by Boxylmer** [JuliaDiff/TaylorSeries.jl#308]
Apologies if this was documented somewhere, but is there a reason `log1p` isn't defined for TaylorSeries objects?

MWE if needed
```Julia
using TaylorSeries

t = Taylor1(4)
tp1 = t + 1
logtp1 = log(tp1)
v = logtp1(0.0001)


t = Taylor1(4)
logtp1 = log1p(t)
logtp1(0.0001) == v
```

**Comment by lbenet** [comment]
Hi! I guess it was a combination of lack of time and attention... 

A straight forward solution could be
```julia
julia> Base.log1p(t::Taylor1{T}) where {T} = log(one(t[0]) + t)

julia> t = Taylor1(16);

julia> log1p(t)
 1.0 t - 0.5 t² + 0.3333333333333333 t³ - 0.25 t⁴ + 0.2 t⁵ - 0.16666666666666666 t⁶ + 0.14285714285714285 t⁷ - 0.125 t⁸ + 0.1111111111111111 t⁹ - 0.1 t¹⁰ + 0.09090909090909091 t¹¹ - 0.08333333333333333 t¹² + 0.07692307692307693 t¹³ - 0.07142857142857142 t¹⁴ + 0.06666666666666667 t¹⁵ - 0.0625 t¹⁶ + 𝒪(t¹⁷)

julia> log1p(-0.5+t)
 - 0.6931471805599453 + 2.0 t - 2.0 t² + 2.6666666666666665 t³ - 4.0 t⁴ + 6.4 t⁵ - 10.666666666666666 t⁶ + 18.285714285714285 t⁷ - 32.0 t⁸ + 56.888888888888886 t⁹ - 102.4 t¹⁰ + 186.1818181818182 t¹¹ - 341.3333333333333 t¹² + 630.1538461538462 t¹³ - 1170.2857142857142 t¹⁴ + 2184.5333333333333 t¹⁵ - 4096.0 t¹⁶ + 𝒪(t¹⁷)

julia> ans(0.05)
-0.5978370007556204

julia> log1p(-0.45)
-0.5978370007556205
```

I hope this helps...

**Comment by Boxylmer** [comment]
Absolutely no big deal at all! I'm floored by this library and cannot thank you all enough for creating and maintaining it. 

Would a longstanding fix require anything special? Correct me if I'm wrong, but I believe `log1p` is special in that it defeats some kind of accuracy or speed issue that arises when using very small values of `x` in the `log(x + 1)` function. It may end up being very difficult mimic that behavior without directly taking the derivative of the `log1p` function, right?


In any case, thank you so much for the quick fix!

**Comment by lbenet** [comment]
I just pushed a commit, including tests, that address the implementation of `log1p`.  At the end, rather than using my previously proposed solution, I've coded it as `log` is; see #317. Any feedback is very appreciated!

Aside from this issue, I plan to include more functions in the package; see #310. Any help is welcome!
