### ISSUE TITLE
Tag a new version

### ISSUE THREAD

**Issue by dpsanders** [JuliaDiff/TaylorSeries.jl#32]
I think we should tag at least a new patch version.

**Comment by lbenet** [comment]
I've been thinking about this as well. Shall we include in the tagged version an improvement related to #24, and perhaps #30 as well?

**Comment by lbenet** [comment]
I will update the documents with the new improvements before tagging a new version

**Comment by lbenet** [comment]
New version is tagged. In the documentation I only updated the bechmarks vs Mathematica (after tagging). I close this
