### ISSUE TITLE
What was breaking in 0.16 and 0.17 ?

### ISSUE THREAD

**Issue by lrnv** [JuliaDiff/TaylorSeries.jl#348]
Hey, 

I have trouble understanding why the PR merged in 0.16 and 0.17 were breaking ?

- If they were not breaking, these releases should have been 0.15.5 and 0.15.6
- If they broke something, I'd like to know what to check that my package test suite (depending on TaylorSeries.jl) covers the change correctly. 

Could you clarify the matter for me please ?

**Comment by lbenet** [comment]
Thanks for reaching out. #347 introduced a new method `zero!` which is widely used now, and #333 a bunch of methods for `Taylor1{TaylorN{T}}` mixtures, aimed to improve performance; you are right that they are not (too) breaking. Also, #346 fixed a Taylor1 constructor bug for mixtures. All that, and still being in major version 0, I think are sufficient for tagging a new minor version. Sorry if that caused troubles in your packages...

**Comment by lrnv** [comment]
There is no troubles in my packages, it is just that i wanted to ensure that the usage I had of TaylorSeries.jl did not broke in a way that i would not test for. 

So if you tell me that nothing was really breaking, this simplifies the matter for me and i'll merge the compat bounds. Thanks a lot for the explanation !

**Comment by lbenet** [comment]
I suggest to have a look on #246, because it fixed a constructor method. Aside from that, I think everything should be fine.

**Comment by lrnv** [comment]
#346 ?

**Comment by PerezHz** [comment]
Maybe worth mentioning: changes introduced by version 0.17 were breaking enough for TaylorIntegration, where we make heavy use of mutating functions and operations on "mixture"-types (e.g., `Taylor1{TaylorN{Float64}}`), and #347 in particular broke some tests where such features are used. But if you're not working with such mixtures, then probably these changes were not breaking for your packages.

**Comment by lbenet** [comment]
If it is ok with you @lrnv, I'll close this issue...

**Comment by lrnv** [comment]
Yes please close. Ty for the details !
