### ISSUE TITLE
TaylorSeries v0.17.7 breaks some tests in TaylorIntegration

### ISSUE THREAD

**Issue by PerezHz** [JuliaDiff/TaylorSeries.jl#359]
When TaylorIntegration tests on current main are run with TaylorSeries v0.17.6 [they pass](https://github.com/PerezHz/TaylorIntegration.jl/actions/runs/9287775483), but when run with v0.17.7 [they fail](https://github.com/PerezHz/TaylorIntegration.jl/actions/runs/9288195881). The failing tests are related to root-finding with `Taylor1{Taylor1{Float64}}`, and are somehow related to evaluation methods (`evaluate!`, `_horner!`, etc.) for this particular mixture.

**Comment by lbenet** [comment]
Thanks for reporting. I'll have a look to see what I broke... sorry.

**Comment by lbenet** [comment]
I think #360 fixes the problems you spotted. Can you check now if it truly solves the issue?

**Comment by PerezHz** [comment]
> I think https://github.com/JuliaDiff/TaylorSeries.jl/pull/360 fixes the problems you spotted. Can you check now if it truly solves the issue?

I just ran the tests and they passed! Many thanks for looking into this!
