### ISSUE TITLE
Why square Jacobians?

### ISSUE THREAD

**Issue by gaperez64** [JuliaDiff/TaylorSeries.jl#371]
Is there a particular reason why you insist on Jacobian matrices being square?

https://github.com/JuliaDiff/TaylorSeries.jl/blob/d9ca58966c8eb65addce02545ff2aa0d21a7fe2c/src/calculus.jl#L255

The usual definition allows for nonsquare Jacobians. Also, in the context of ODEs, if you have a time variable `t` then you'll end up with more variables than equations, right?

**Comment by lbenet** [comment]
Thanks for opening this issue, and good catch! There is no real reason... If you have some time, please, open a PR solving this.

**Comment by lbenet** [comment]
I think `jacobian` is used in both contexts: as a matrix of the derivatives of a vector of functions, or as that matrix evaluated at a given point, which is what we consider. If you have a better name, I'm open for suggestions, which the could allow us to have it exported (the reason it is not exported is to avoid naming collisions with other packages).

**Comment by lbenet** [comment]
Closed by #372
