### ISSUE TITLE
Change evalTaylor by evaluate

### ISSUE THREAD

**Issue by dapias** [JuliaDiff/TaylorSeries.jl#39]
In the *User guide.ipynb* the function `evalTaylor` is suggested but instead  `evaluate` is used. It is critical in the *KeplerProblem.ipynb* example where `evalTaylor` is inside the function **TaylorStepper** but it is not  defined in the source files anymore.

**Comment by lbenet** [comment]
Thanks for noticing this! You are right, `evaluate` is the correct function.

 Would you mind to make a pull request with the corrections in the documentation and in the Kepler integration notebook?

**Comment by dapias** [comment]
Sure. I already did that.

**Comment by lbenet** [comment]
Closing, since this is already implemented in #40. Thanks!

**Comment by lbenet** [comment]
I forgot closing this...
