### ISSUE TITLE
Rational coefficients for sin?

### ISSUE THREAD

**Issue by dpsanders** [JuliaDiff/TaylorSeries.jl#51]
Can we get the following to produce rational coefficients for sin.
```
julia> t = taylor1_variable(Rational{Int}, 10)
 1//1 t + 𝒪(t¹¹)

julia> sin(t)
 1.0 t - 0.16666666666666666 t³ + 0.008333333333333333 t⁵ - 0.0001984126984126984 t⁷ + 2.7557319223985893e-6 t⁹ + 𝒪(t¹¹)
```

**Comment by lbenet** [comment]
The reason that it does not yield (directly) a `Taylor1{Rational{Int64}}` result is because, in general, `sin` should return a real value (and not a rational). 

Yet, the following works:
```julia
julia> convert(Taylor1{Rational{Int}},sin(t))
 1//1 t - 1//6 t³ + 1//120 t⁵ - 1//5040 t⁷ + 1//362880 t⁹ + 𝒪(t¹¹)
```

**Comment by dpsanders** [comment]
I'm not sure what you mean when you say that sin should return a real value - the Taylor expansion just gives coefficients of the Taylor polynomial, which should be exact if I ask for rationals. 

The evaluate function should certainly return a float in any case if I pass it a float as it's argument.

**Comment by dpsanders** [comment]
Actually I wonder if it doesn't make sense for the coefficients to be rationals by default. In any case it should certainly be possible to get them without an explicit convert (which presumably uses a dangerous rationalize)

**Comment by lbenet** [comment]
My point is illustrated as follows:
```julia
julia> sin(1//1)
0.8414709848078965
```
In general, the result of trascendental functions are real, not rationals, so it makes sense the `Float64` returned value. In some cases, you may get nice expansions, e.g. `sin(t)` around 0, but this must not be the case in general.

**Comment by dpsanders** [comment]
Are you saying that the coefficients in the expansion will not be rational? I don't see why that would happen. The Taylor expansion (Taylor polynomial) and the function are two different things.

**Comment by dpsanders** [comment]
Ah, maybe when you expand sin (1+t) around 1?

**Comment by lbenet** [comment]
Yes, that's my point; sorry to be so cryptic. In general, when you expand around some t_0 you don't get rational coefficients.

**Comment by lbenet** [comment]
Closing this.
