### ISSUE TITLE
New test failure on PackageEvaluator

### ISSUE THREAD

**Issue by tkelman** [JuliaDiff/TaylorSeries.jl#53]
Ref http://pkg.julialang.org/detail/TaylorSeries.html, this might be spurious but it surprised me a bit so figured I'd file an issue and let you know. I don't think any of your dependencies have changed versions recently, other than Compat? Would be unfortunate if something changed the meaning of code there.

**Comment by lbenet** [comment]
Thanks for the note. Master seems to behave correctly; I'm not sure what caused the problem. I guess tagging a new version would be the simplest thing to do, isn't it?

**Comment by tkelman** [comment]
Probably! You know better than I do what you've changed since your last tag.

**Comment by lbenet** [comment]
Closing; v0.2.0 is merged. Thanks a lot!
