### ISSUE TITLE
Tests not passing in v0.4

### ISSUE THREAD

**Issue by lbenet** [JuliaDiff/TaylorSeries.jl#54]
I just noticed that tests are not passing for v0.2.0 of `TaylorSeries.jl` on Julia v0.4, when they actually did; something alike is happening in v0.1.2 with Julia v0.3.

The following is taken from [these logs](http://pkg.julialang.org/detail/TaylorSeries.html):
```
Julia v0.3

2016-06-17 to 2016-06-26, v0.1.2, Tests fail.
2016-05-08 to 2016-06-16, v0.1.2, Tests pass.
...

Julia v0.4

2016-06-26 to 2016-06-26, v0.2.0, Tests fail.
2016-06-22 to 2016-06-25, v0.2.0, Tests pass.
...
```

 I have no clue what might have happened. 
CC: @tkelman

**Comment by dpsanders** [comment]
I restarted the Travis run and it now seems to pass:

https://travis-ci.org/JuliaDiff/TaylorSeries.jl/builds/139192112

**Comment by lbenet** [comment]
The weird thing is that tests previously passed (in Julia v0.3 and 0.4) as it can be seen above, but the last time that PackageEvaluator ran, they didn't.

**Comment by dpsanders** [comment]
I don't know what's going on, but maybe we shouldn't worry too much about it.

**Comment by lbenet** [comment]
Seems that whatever happened with v0.4 was corrected (today); still there is something weird for v0.1.2 (with Julia 0.3), but we can leave this out, since we are not supporting anymore that Julia version. 

I'm closing this.

**Comment by lbenet** [comment]
Thanks Tony for keeping an eye on this. 

Precisely because we are not supporting Julia 0.3 anymore I closed this.

**Comment by tkelman** [comment]
Looks okay on master of Compat.jl, so I'll tag a new version there and hope things get back to normal by tomorrow.

**Comment by lbenet** [comment]
Thanks again!
