### ISSUE TITLE
Some expansions don't conserve type

### ISSUE THREAD

**Issue by blas-ko** [JuliaDiff/TaylorSeries.jl#66]
So, I define: 
```julia
using TaylorSeries 

 t = Taylor1([0,1//1],5)
 #Out: 1//1 t + 𝒪(t⁶)

t^2
#Out: 1//1 t^2 + 𝒪(t⁶)
# which works for squaring t

exp(t)
#Out: 1.0 + 1.0 t + 0.5 t² + 0.16666666666666666 t³ + 0.041666666666666664 t⁴ + 0.008333333333333333 t⁵ + 𝒪(t⁶) 
# which isn't what would I would expect
````

I would expect
```julia
exp(t)
#Out: 1//1 + 1//1 t + 1//2 t² + 1//6 t³ + 1//24 t⁴ + 1//120 t⁵ + 𝒪(t⁶)
````

I know I could use `convert(Taylor1{Rational{Int64}},exp(t))`, but it's unconfortable.

**Comment by lbenet** [comment]
This is actually intended, though this may sound strange. 

Essentially it reflects the fact that `exp(1//1)` returns a `Float64`, and not a `Rational{Int64}`. Note that `exp(1//1)` is actually an irrational number. Despite of this, as far as I have checked, the implementation is type stable.

See #56 for a long discussions on this, and perhaps #59 as well.

**Comment by blas-ko** [comment]
Perfect, understood! 
Closing this issue.
