### ISSUE TITLE
Add `jacobian!`

### ISSUE THREAD

**Issue by PerezHz** [JuliaDiff/TaylorSeries.jl#88]
Related to [TaylorIntegration's PR #18](https://github.com/PerezHz/TaylorIntegration.jl/pull/18). For performance reasons, it would be good to have an in-place evaluation version of `jacobian` in TaylorSeries. My proposal is something like this:

```julia
function jacobian!{T<:Number}(jjac::Array{T,2}, vf::Array{TaylorN{T},1})
    numVars = get_numvars()
    @assert length(vf) == numVars

    for comp = 1:numVars
        jjac[comp,:] = vf[comp].coeffs[2].coeffs[1:end]
    end

    nothing
end
```

As far as I've tested it, this change improves memory use on TaylorIntegration Lyapunov spectrum methods, in particular `stabilitymatrix!`, where `jacobian` is currently used.. Perhaps this could be included in #87 ?

**Comment by PerezHz** [comment]
This version is even faster:

```julia
function jacobian!{T<:Number}(jjac::Array{T,2}, vf::Array{TaylorN{T},1})
    numVars = get_numvars()
    @assert length(vf) == numVars

    for comp1 = 1:numVars
        for comp2 = 1:numVars
            jjac[comp1,comp2] = vf[comp1].coeffs[2].coeffs[comp2]
        end
    end

    nothing
end
```

**Comment by lbenet** [comment]
Can you send a PR, with tests? I'm actually spending some time in this kind of tricks...

**Comment by lbenet** [comment]
Regarding #87, if you are in a hurry, just send it using the current master.

**Comment by PerezHz** [comment]
PR #91 is an attempt to implement inplace evaluation versions of `jacobian` and `hessian`  😄

**Comment by PerezHz** [comment]
Closed by PR #91

**Comment by lbenet** [comment]
Done it, though not in a clean way; you'll have to `git pull -f`...

**Comment by lbenet** [comment]
... on that branch
