### ISSUE TITLE
Define getindex for Taylor

### ISSUE THREAD

**Issue by dpsanders** [JuliaDiff/TaylorSeries.jl#96]
Perhaps a simpler solution for the `fixorder` part of #95  is to define `getindex` for a `Taylor1` as
```
julia v0.5> Base.getindex(t::Taylor1, i::Integer) = i <= length(t.coeffs) ? t.coeffs[i] : zero(eltype(t))
```

**Comment by lbenet** [comment]
I think I understand your point here, which in a way mimics `get_coeff(a::Taylor1, order::Int)`, except that it throws an error in case of `order` is out of range (the range is from 0 to `order` of the polynomial).

So far, `fixorder` is helpful simply because I'm lazy to program a method when a.order < b.order, another when both are equal, and a third when the inequality goes the other way around.

**Comment by dpsanders** [comment]
Right, with `getindex` you should just be able to just check `a[i] == b[i]` for `i in 1:max(length(a), length(b))`.

**Comment by dpsanders** [comment]
`get_coeff` should definitely be replaced by `getindex` in any case. Then you can just do `a[i]` instead of `get_coeff(a, i)`!

**Comment by lbenet** [comment]
> Right, with `getindex` you should just be able to just check `a[i] == b[i]` for i in `1:max(length(a), length(b))`.

I guess you speak of `==`, don't you? Yet, the multiplication is nasty; it can be done, but as I said, I was lazy.

> `get_coeff` should definitely be replaced by `getindex` in any case. Then you can just do `a[i]` instead of `get_coeff(a, i)`!

That's a good point.

**Comment by dpsanders** [comment]
Shall I make a PR to replace `get_coeff`?

**Comment by lbenet** [comment]
Sure! It is simply more comfortable, and allows easy reading! Thanks!

**Comment by dpsanders** [comment]
I will wait til after #95 is merged.

**Comment by dpsanders** [comment]
I see that `get_coeff` is not actually used that much. But many of the `a.coeffs[i]` things could then be replaced by `a[i]`.

**Comment by dpsanders** [comment]
Done in #97.

**Comment by lbenet** [comment]
Closing, since #97 is merged.
